### ISSUE TITLE
data is mixed when there are two buttons

### ISSUE THREAD

**Issue by jemoii** [kapantzak/SearchAreaControl#13]
I have two buttons in the same dialog,

> editMessageForm.find('a[name=openCountryPanel]').searchAreaControl({
> 	data: editMessageDialog.regionCountriesList
> });

> editMessageForm.find('a[name=openDevicePanel]').searchAreaControl({
> 	data: editMessageDialog.projectDevicesList
> });

The first one is to select country, and the next is to select device.

When I click on the first one, it shows country data successfully, but when I click on the next, the country data which should be in the first one come into it.

Hope you can review this problem.

**Comment by kapantzak** [comment]
Corrected the deep copy of default object with user provided options
`this.opt = $.extend(true, {}, $.fn[pluginName].defaults, options);`

**Comment by jemoii** [comment]
It works fine now, thank you very much.
