### ISSUE TITLE
Setting initial selected nodes

### ISSUE THREAD

**Issue by Rapid0s** [kapantzak/SearchAreaControl#23]
When I try to use  "afterinit" event with the setSelectedNodes  method
it does not seem to work.

If I trigger the method with setTimeout with 1 ms delay it actually does 
what its supposed to do.

**Comment by kapantzak** [comment]
Hi @Rapid0s, sorry for the delayed response.
If I understand correctly, you want to select some nodes.
You could initialize the plugin and then call `'setSelectedNodes'` without using the `'searchareacontrol.afterinit'` event, like this:

     var btn = $('#myButton');
     btn.searchAreaControl({...});
     btn.searchAreaControl('setSelectedNodes', ...);

**Comment by kapantzak** [comment]
It seems that, right now, `searchareacontrol.afterinit` event gets activated too soon.
I will try to change the time of trigering this event, and also add a new option of pre-selecting one or more nodes on plugin initialization in one of the upcoming releases.

**Comment by kapantzak** [comment]
@Rapid0s I've released version 2.1.0 with the following changes:

- `searchareacontrol.afterinit` event an be used to pre-select one or more nodes (gets fired inside a setTimeout)
- Added new option `selectedNodes` in order to provide an array of nodes to be pre-selected
