### ISSUE TITLE
Wildchar support

### ISSUE THREAD

**Issue by literakl** [kapantzak/SearchAreaControl#24]
Hi, this plugin looks awesome. Would it be possible to add another filtering option - wildchars? Our dataset is huge and users are programmers. They would appreciate advanced queries like "CZ%Unit" matching "CZ SK Unit" or "Czech Unit". Thanks for consideration.

**Comment by kapantzak** [comment]
Hello literalk, sorry for late response. Wildcar support would actually be a great feature! I will try to add this feature to one of the following versions.. Thanks for proposal!

**Comment by kapantzak** [comment]
Added regular expression search.
Needs to be tested

**Comment by literakl** [comment]
thank you, looking forward for a release

**Comment by kapantzak** [comment]
Regular expression search availbale in version 1.5.0
