### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by jonathands** [kapantzak/SearchAreaControl#36]
I'm using the plugin in an internatal product and am going to need to translate the messages and buttons, I notice  there is yet no i18n standart in place, instead of hardcoding it I meant to do some proper i18n. 

@kapantzak , do you have some standart or idea for translating the plugin that you prefer to follow?

I'm not sure this is the proper place to discuss this, if not please point me to the right direction

**Comment by kapantzak** [comment]
@jonathands thank you for using searchAreaControl plugin. Unfortunatelly, there is no localization method implemented yet, but I will, definitely try to find some time to include a i18n standard in on of the upcoming releases.

**Comment by jonathands** [comment]
@kapantzak  I'm using it like this:

https://github.com/jonathands/SearchAreaControl/tree/master/searchAreaControl

I don't know if tis is the best approach, if you want me to I can push it to your repo

**Comment by kapantzak** [comment]
@jonathands I've just commited a new release (2.0.0) that includes localization functionality. You can refer to README file for more information. Please do not hesitate to contact me if any problem occurs.
