### ISSUE TITLE
Close modal without modifying main button

### ISSUE THREAD

**Issue by thatdavecarter** [kapantzak/SearchAreaControl#58]
Hi :)

Recently starting using this control, and think it's great! However, one enhancement to consider implementing is having a button to close out the modal without updating the main button.

Thanks again for the great control!

**Comment by kapantzak** [comment]
Hello!
First of all, thanks for using the plugin!
I've just implemented this behaviour in the last release (v2.2.0). `Cancel` button is added to the popup buttons collection, which closes the popup without updating the last selection.
The option is `popupButtons.cancel` and you can fing information in the README [https://github.com/kapantzak/SearchAreaControl#popupbuttonscancel](url)
_Note: the button is hidden by default, so you have to set it as visible_
