### ISSUE TITLE
Select all - Select only highlighted items

### ISSUE THREAD

**Issue by thatdavecarter** [kapantzak/SearchAreaControl#66]
Is it possible to add enhance the functionality of the select all button (or implement a new button) to enable selection of the sac-found-item nodes? 

For example, I search "Compact" which highlights the node items as follows
![image](https://user-images.githubusercontent.com/3129422/37652574-df81913c-2c33-11e8-9f10-4421f1460995.png)

However, clicking select all selects all nodes contained within the parents whether they match the search or not:

![image](https://user-images.githubusercontent.com/3129422/37652626-0478296a-2c34-11e8-8ba7-5f9d5c2ef9bc.png)

Thanks

Dave

**Comment by kapantzak** [comment]
Hello Dave,

Thanks for your contibution. I've already released version 2.5.0 that includes `selectHighlighted` button, as you mentioned.
Check the upadted documentation ([https://github.com/kapantzak/SearchAreaControl#select-highlighted-button](url)) for more details.
