### ISSUE TITLE
searchAreaControl not working in IE

### ISSUE THREAD

**Issue by khalilTN** [kapantzak/SearchAreaControl#72]
Line 1105
`var instance = $.data(this, 'plugin_' + pluginName) `
returns undefined on IE, can you help me ?
Thanks

**Comment by khalilTN** [comment]
Hello
IE version  11.407
Sometimes it works, especially when a breakpoint is set on the searchAreaControl function call, but most of time it does not

**Comment by khalilTN** [comment]
> Hello
> IE version 11.407
> Sometimes it works, especially when a breakpoint is set on the searchAreaControl function call, but most of time it does not.

**Comment by khalilTN** [comment]
Closed by mistake

**Comment by kapantzak** [comment]
Are you sure that the target element is present and visible at the time of plugin initialization? Try executing the initialization inside a setTimeout callback after 2 or 3 seconds.
Can you provide the code? It seems that there is no problem to me, even in IE9.
You can check the demo page in IE and verify that it successfully gets initialized in IE.

**Comment by kapantzak** [comment]
Closing issue as inactive
