### ISSUE TITLE
Disable scroll of browser window

### ISSUE THREAD

**Issue by LennyLip** [kapantzak/SearchAreaControl#77]
When modal SearchAreaControl is showing the scroll feature for background browser window is still working.

https://kapantzak.github.io/SearchAreaControl/

**Comment by LennyLip** [comment]
![scroll](https://user-images.githubusercontent.com/955994/54267230-eff29780-4589-11e9-870a-42c16f32c4eb.gif)

**Comment by kapantzak** [comment]
Fixed in version 2.8.1
